# namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: viz-rbac

---
# service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-sa
  namespace: viz-rbac

---
# cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-crole
  namespace: viz-rbac
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods", "serviceaccounts"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests", "certificatesigningrequests/approval", "certificatesigningrequests/status"]
  verbs: ["*"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["signers"]
  resourceNames: ["kubernetes.io/kube-apiserver-client"] # Change domain name & signer
  verbs: ["*"]

---
# crole-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-crolebinding
  namespace: viz-rbac
subjects:
- kind: ServiceAccount
  name: api-sa
  namespace: viz-rbac
roleRef:
  kind: ClusterRole
  name: api-crole
  apiGroup: rbac.authorization.k8s.io

---
# api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: viz-rbac-api
  namespace: viz-rbac
  labels:
    app: viz-rbac-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: viz-rbac-api
  template:
    metadata:
      labels:
        app: viz-rbac-api
    spec:
      serviceAccountName: api-sa
      containers:
      - name: viz-rbac-api
        image: freckie/viz-rbac-api:0.0.1
        imagePullPolicy: Always # for development. use IfNotPresent for production
        ports:
        - name: http
          containerPort: 8000
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /api/res/v1/namespaces
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10

---
# api-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: viz-rbac-api
  namespace: viz-rbac
  labels:
    app: viz-rbac-api
spec:
  type: NodePort
  selector:
    app: viz-rbac-api
  ports:
  - name: http
    port: 30011
    targetPort: 8000
    nodePort: 30011

---
# web-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: viz-rbac-web
  namespace: viz-rbac
  labels:
    app: viz-rbac-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: viz-rbac-web
  template:
    metadata:
      labels:
        app: viz-rbac-web
    spec:
      serviceAccountName: default
      containers:
      - name: viz-rbac-web
        image: freckie/viz-rbac-web:0.0.1
        imagePullPolicy: Always # for development. use IfNotPresent for production
        ports:
        - name: http
          containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
# web-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: viz-rbac-web
  namespace: viz-rbac
  labels:
    app: viz-rbac-web
spec:
  type: NodePort
  selector:
    app: viz-rbac-web
  ports:
  - name: http
    port: 30010
    targetPort: 80
    nodePort: 30010
